### ISSUE TITLE
Leaderboard - SocialNetwork question

### ISSUE THREAD

**Issue by vladanminic** [fi-content2-games-platform/FIcontent.Gaming.Enabler.Leaderboard#6]
Dear Leaderboard team,

in order to connect Leaderboard SE with my Social Network SE (both installed on my Ubuntu VM instance), is it enough just to uncomment this line https://github.com/fi-content2-games-platform/FIcontent.Gaming.Enabler.Leaderboard/blob/master/leaderboard-standalone/bin/config.properties#L14  and to change address, or something else need to be done?

Can you explain a little bit how Leaderboard communicate with PPnet? Does it automatically post results on Social Network or I'm wrong? What username (and pass) it uses to submit result on SN?

And last question, is there any option to connect LeaderBoard wit KeyRock IDM?

Thank you in advance!

Best regards,
Vladan

**Comment by vaifrax** [comment]
The leaderboard automatically posts, if a different person gets the highest score.
The KeyRock IDM is only used to display user profile images. A simple password authentication was added.
Closing as issues are successfully resolved now.
